const defaults = require("@wordpress/scripts/config/webpack.config");
const path = require("path");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const isLegacy = process.env.BUILD_TARGET === "legacy";

const banner = `
CampaignBay
Copyright (c) 2025 WP Anchor Bay - https://wpanchorbay.com

This software is licensed under the GPLv2 or later.
This file is generated from un-compiled source code. Do not edit this file directly.

Source Code (Root): https://github.com/dipta-sdd/campaignbay/tree/release-1.0.0/
Source Code (Admin): https://github.com/dipta-sdd/campaignbay/tree/release-1.0.0/src/admin

For license information please see [name].js.LICENSE.txt
`;

module.exports = isLegacy
  ? {
      entry: {
        admin: "./src/admin/index.js",
      },
      output: {
        path: path.resolve(__dirname, "build"),
        filename: "[name]-legacy.js",
        clean: false,
      },
      devtool: false,
      module: {
        rules: [
          {
            test: /\.js$/,
            exclude: /node_modules/,
            use: "babel-loader",
          },
          {
            test: /\.scss$/,
            use: [
              MiniCssExtractPlugin.loader,
              "css-loader",
              "postcss-loader",
              "sass-loader",
            ],
          },
          {
            test: /\.svg$/,
            type: "asset/resource", // Use Webpack 5's built-in asset handler.
            generator: {
              // This ensures the output file has a readable name and is placed in an 'images' folder.
              filename: "images/[name][ext]",
            },
          },
        ],
      },
      plugins: [
        new MiniCssExtractPlugin({
          filename: "[name].css",
        }),
      ],
    }
  : {
      ...defaults,
      externals: {
        react: "React",
        "react-dom": "ReactDOM",
      },
      entry: {
        admin: "./src/admin/index.js",
      },
      output: {
        ...defaults.output,
        filename: "[name].js",
        clean: false,
      },
    };
