<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1a72b9b484af8f73bc6b3df50d046dff
{
    public static $files = array (
        '5cd7442f2121b4f5a33738853ccb5986' => __DIR__ . '/../..' . '/app/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WpabCb\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WpabCb\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'WpabCb\\Admin\\Admin' => __DIR__ . '/../..' . '/app/Admin/Admin.php',
        'WpabCb\\Api\\ApiController' => __DIR__ . '/../..' . '/app/Api/ApiController.php',
        'WpabCb\\Api\\CampaignsController' => __DIR__ . '/../..' . '/app/Api/CampaignsController.php',
        'WpabCb\\Api\\SettingsController' => __DIR__ . '/../..' . '/app/Api/SettingsController.php',
        'WpabCb\\Core\\Activator' => __DIR__ . '/../..' . '/app/Core/Activator.php',
        'WpabCb\\Core\\Common' => __DIR__ . '/../..' . '/app/Core/Common.php',
        'WpabCb\\Core\\Deactivator' => __DIR__ . '/../..' . '/app/Core/Deactivator.php',
        'WpabCb\\Core\\I18n' => __DIR__ . '/../..' . '/app/Core/I18n.php',
        'WpabCb\\Core\\Loader' => __DIR__ . '/../..' . '/app/Core/Loader.php',
        'WpabCb\\Core\\Plugin' => __DIR__ . '/../..' . '/app/Core/Plugin.php',
        'WpabCb\\Data\\DbManager' => __DIR__ . '/../..' . '/app/Data/DbManager.php',
        'WpabCb\\Data\\PostTypes' => __DIR__ . '/../..' . '/app/Data/PostTypes.php',
        'WpabCb\\Engine\\Campaign' => __DIR__ . '/../..' . '/app/Engine/Campaign.php',
        'WpabCb\\Engine\\CampaignManager' => __DIR__ . '/../..' . '/app/Engine/CampaignManager.php',
        'WpabCb\\Engine\\PricingEngine' => __DIR__ . '/../..' . '/app/Engine/PricingEngine.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1a72b9b484af8f73bc6b3df50d046dff::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1a72b9b484af8f73bc6b3df50d046dff::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1a72b9b484af8f73bc6b3df50d046dff::$classMap;

        }, null, ClassLoader::class);
    }
}
